# -*- coding: utf-8 -*-
"""food_predict

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0ItsIdy7bDfiDv3FXD_4OMfcCgC6NAX
"""

!nvidia-smi

import os
import zipfile
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/Tibame/dataset/food_image.zip'

zip_ref = zipfile.ZipFile(path, 'r')
zip_ref.extractall('/tmp')
zip_ref.close()

os.chdir('/tmp')
os.listdir('/tmp')

# import library
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import load_model
from tensorflow.python.keras.preprocessing import image
import numpy as np

# load model
model = load_model('model-food-final.h5')
# pd.read_pickle('./food_train_model.pkl')

# load images
test_dataset_path = '/tmp/food_test/'
test_filenames = os.listdir(test_dataset_path)
test_df = pd.DataFrame({'filename': test_filenames})
nb_samples = test_df.shape[0]
test_gen = ImageDataGenerator(rescale=1./255)
test_generator = test_gen.flow_from_dataframe(test_df, 
    test_dataset_path, 
    x_col='filename',
    y_col=None,
    class_mode=None,
    batch_size=7,
    target_size=(200, 200),
    shuffle=False)

# predict the category
# labels = ['apple','cabbage','carrot','chicken','cucumber','egg','mushroom','potato','radish','tomato']
predict = model.predict_generator(test_generator, steps=np.ceil(nb_samples/batch_size))
test_df['category'] = pd.DataFrame(np.argmax(predict, axis=1))

for i in test_df['category']:
  if i == 0:
    print('apple')
  elif i == 1:
    print('cabbage')
  elif i == 2:
    print('carrot')
  elif i == 3:
    print('chicken')
  elif i == 4:
    print('cucumber')
  elif i == 5:
    print('egg')
  elif i == 6:
    print('mushroom')
  elif i == 7:
    print('potato')
  elif i == 8:
    print('radish')
  elif i == 9:
    print('tomato')
  else: 
    print('圖片無法辨識，請輸入文字...')

